optimizer:
  type: AdamW
  freeze: 0
  kwargs:
    lr: 1e-4
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 200
    initial_epochs: 5.
    lr_min: 1e-6
    warmup_lr_init: 1e-6
    cycle_limit: 1

dataset:
  train:
    _base_: scripts/pretrain_1212/benchmark_pretrain_maskratio_50_fusion_16_binary_downsample_16_batchsize_128_epoch_200_lr_1e-4/HistMol_pretrain_lowres_benchmark.yaml
    others:
      subset: pretrain
      if_abmil: False
  val:
    _base_: scripts/pretrain_1212/benchmark_pretrain_maskratio_50_fusion_16_binary_downsample_16_batchsize_128_epoch_200_lr_1e-4/HistMol_pretrain_lowres_benchmark_test.yaml
    others:
      subset: test
      if_abmil: False

model:
  NAME: Squall
  img_size: 224
  expr_size: 56
  expr_chans: 15757
  down_sample: 16
  mask_ratio: 0.5
  embed_dim: 1024
  depth: 24
  merge_layer_depth: 16
  drop_path_rate: 0.1
  num_heads: 16
  pos_type: mlp
  decoder_depth: 4
  PE_type: "RPB"
  if_rpb: True

train_test_split: /mnt/histMol/lowres_data/label/benchmark_datanorm_tissue_12_1.json
total_bs: 128
step_per_update: 1
max_epoch: 200
if_validate: False
if_abmil: False